// Free Chat — open-ended English conversation with a persona-driven AI partner.
//
// Layout mirrors components/exercises/RoleplayChat.tsx (iMessage bubbles, yellow
// user / black AI, BLUE accents). Differs from RoleplayChat in that there's
// no scripted turn list — every AI reply is generated by lib/llm-router's
// chatComplete().
//
// Persistence:
//   lafla.freechat.session              -> JSON ChatMessage[] (current session)
//   lafla.freechat.persona              -> persona id (string)
//   lafla.freechat.dailyCount.YYYY-MM-DD -> number (free-tier daily user msg cap)
//
// Daily free-tier cap: 10 user messages / day. After that we show a paywall CTA
// in place of the input bar (the cap resets at local midnight by date key).

import { useEffect, useMemo, useRef, useState } from "react";
import {
  View,
  Text,
  TextInput,
  Pressable,
  ScrollView,
  StyleSheet,
  Modal,
  Alert,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
} from "react-native";
import { StatusBar } from "expo-status-bar";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { tokens } from "../theme";
import { speak } from "../lib/tts";
import { chatComplete } from "../lib/llm-router";
import type { ChatMessage } from "../lib/llm-types";

// ---------------------------------------------------------------------------
// Storage keys
// ---------------------------------------------------------------------------

const K_SESSION = "lafla.freechat.session";
const K_PERSONA = "lafla.freechat.persona";
const K_DAILY_PREFIX = "lafla.freechat.dailyCount."; // + YYYY-MM-DD
const DAILY_LIMIT = 10;

function todayKey(): string {
  // Local-time YYYY-MM-DD so the limit resets at midnight in user's TZ.
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

// ---------------------------------------------------------------------------
// Personas
// ---------------------------------------------------------------------------

interface Persona {
  id: string;
  emoji: string;
  /** Short Turkish label shown in selector / header. */
  label: string;
  /** One-line Turkish blurb shown under the name. */
  setting: string;
  /** Greeting the AI "speaks" first when a new session starts. */
  opener: string;
  /** System prompt sent to chatComplete. Turkish-flavored English instructions. */
  systemPrompt: string;
}

// Shared instructions appended to each persona prompt — keeps the assistant
// honest about the learner's level and language.
const LEARNER_NOTE = `
The user is a Turkish native speaker learning English (B1 level). Always reply in English. Keep replies short (1-3 sentences). Use common vocabulary. End almost every reply with a friendly follow-up question to keep the chat going. If the user writes in Turkish, gently nudge them back to English with a quick example. Never use markdown, code blocks, or bullet lists.`.trim();

const PERSONAS: Persona[] = [
  {
    id: "bartender",
    emoji: "🍷",
    label: "Bartender",
    setting: "Bir barda sohbet ediyorsun",
    opener: "Hey there! What can I get you tonight? Long day?",
    systemPrompt: `You are a friendly, slightly cheeky bartender at a cozy neighborhood bar. Make small talk about the user's day, drinks, music, sports — light, fun, encouraging. ${LEARNER_NOTE}`,
  },
  {
    id: "manager",
    emoji: "💼",
    label: "Manager (1:1)",
    setting: "Yöneticinle birebir görüşme",
    opener:
      "Hi, thanks for jumping on this 1:1. How's the week going so far?",
    systemPrompt: `You are a supportive but professional manager running a weekly 1:1 with a direct report. Ask about progress, blockers, wins, career goals. Use business-casual English. ${LEARNER_NOTE}`,
  },
  {
    id: "date",
    emoji: "💕",
    label: "Date partner",
    setting: "İlk buluşmada tanışıyorsunuz",
    opener:
      "Hey, finally! You found the place okay? I was nervous you'd get lost.",
    systemPrompt: `You are on a friendly first date with the user. Be warm, curious, a little flirty but always respectful. Ask about hobbies, travel, food, dreams. Light, playful tone. ${LEARNER_NOTE}`,
  },
  {
    id: "stranger",
    emoji: "🚶",
    label: "Casual stranger",
    setting: "Otobüste yan koltukta bir yabancı",
    opener:
      "Hey, sorry — is this seat taken? Long ride today, huh?",
    systemPrompt: `You are a friendly stranger sitting next to the user on a long bus / train ride. Make easy small talk: weather, the trip, where they're from, music in their earbuds. ${LEARNER_NOTE}`,
  },
  {
    id: "interview",
    emoji: "🎯",
    label: "Interview coach",
    setting: "Mülakat koçu prova yapıyor",
    opener:
      "Great, let's start. Tell me a little about yourself — keep it under a minute.",
    systemPrompt: `You are an English-speaking interview coach helping the user practice common job interview questions. Ask one question at a time, then give a short, encouraging note on their previous answer (grammar or content) before the next question. ${LEARNER_NOTE}`,
  },
];

function findPersona(id: string | null | undefined): Persona {
  return PERSONAS.find((p) => p.id === id) ?? PERSONAS[0]!;
}

// ---------------------------------------------------------------------------
// Local message shape (separate from llm-types ChatMessage so we can carry
// transient flags like "error" without leaking them to the API).
// ---------------------------------------------------------------------------

interface UiMessage {
  role: "user" | "assistant";
  content: string;
  error?: boolean;
}

const ERROR_FALLBACK = "Şu an AI hizmeti kullanılamıyor, biraz sonra dene.";

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

export default function FreeChatScreen() {
  const router = useRouter();
  const [personaId, setPersonaId] = useState<string>(PERSONAS[0]!.id);
  const [messages, setMessages] = useState<UiMessage[]>([]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [dailyCount, setDailyCount] = useState(0);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const scrollRef = useRef<ScrollView>(null);

  const persona = useMemo(() => findPersona(personaId), [personaId]);
  const atLimit = dailyCount >= DAILY_LIMIT;

  // -------------------------------------------------------------------------
  // Hydrate persona + session + daily count on mount.
  // -------------------------------------------------------------------------
  useEffect(() => {
    (async () => {
      try {
        const [storedPersona, storedSession, storedCount] = await Promise.all([
          AsyncStorage.getItem(K_PERSONA),
          AsyncStorage.getItem(K_SESSION),
          AsyncStorage.getItem(K_DAILY_PREFIX + todayKey()),
        ]);

        const pid = storedPersona && PERSONAS.some((p) => p.id === storedPersona)
          ? storedPersona
          : PERSONAS[0]!.id;
        setPersonaId(pid);

        if (storedSession) {
          try {
            const parsed = JSON.parse(storedSession) as UiMessage[];
            if (Array.isArray(parsed) && parsed.length > 0) {
              setMessages(parsed);
            } else {
              seedOpener(pid);
            }
          } catch {
            seedOpener(pid);
          }
        } else {
          seedOpener(pid);
        }

        const n = storedCount ? parseInt(storedCount, 10) : 0;
        setDailyCount(Number.isFinite(n) && n > 0 ? n : 0);
      } catch {
        seedOpener(PERSONAS[0]!.id);
      } finally {
        setHydrated(true);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Helper used only during hydration / new-session resets.
  const seedOpener = (pid: string) => {
    const p = findPersona(pid);
    setMessages([{ role: "assistant", content: p.opener }]);
  };

  // -------------------------------------------------------------------------
  // Persist session whenever it changes (after hydration). We avoid writing
  // during the initial render because hydrate already populated state.
  // -------------------------------------------------------------------------
  useEffect(() => {
    if (!hydrated) return;
    void AsyncStorage.setItem(K_SESSION, JSON.stringify(messages)).catch(
      () => {},
    );
  }, [messages, hydrated]);

  // -------------------------------------------------------------------------
  // Auto-scroll to bottom on new content.
  // -------------------------------------------------------------------------
  useEffect(() => {
    const t = setTimeout(
      () => scrollRef.current?.scrollToEnd({ animated: true }),
      80,
    );
    return () => clearTimeout(t);
  }, [messages, sending]);

  // -------------------------------------------------------------------------
  // Actions
  // -------------------------------------------------------------------------

  const handlePersonaSelect = (id: string) => {
    setPickerOpen(false);
    if (id === personaId) return;
    Alert.alert(
      "Yeni partner",
      "Mevcut sohbet sıfırlanacak. Devam edilsin mi?",
      [
        { text: "Vazgeç", style: "cancel" },
        {
          text: "Evet",
          onPress: async () => {
            setPersonaId(id);
            await AsyncStorage.setItem(K_PERSONA, id).catch(() => {});
            const p = findPersona(id);
            setMessages([{ role: "assistant", content: p.opener }]);
          },
        },
      ],
    );
  };

  const handleNewSession = () => {
    Alert.alert(
      "Yeni sohbet",
      "Mevcut konuşma silinecek. Devam edilsin mi?",
      [
        { text: "Vazgeç", style: "cancel" },
        {
          text: "Yeni başla",
          style: "destructive",
          onPress: () => {
            setMessages([{ role: "assistant", content: persona.opener }]);
          },
        },
      ],
    );
  };

  const sendMessage = async () => {
    const text = input.trim();
    if (!text || sending || atLimit) return;

    // Optimistic append + clear input.
    const userMsg: UiMessage = { role: "user", content: text };
    const nextMessages: UiMessage[] = [...messages, userMsg];
    setMessages(nextMessages);
    setInput("");
    setSending(true);

    // Increment daily count (count user messages, not AI replies).
    const newCount = dailyCount + 1;
    setDailyCount(newCount);
    void AsyncStorage.setItem(
      K_DAILY_PREFIX + todayKey(),
      String(newCount),
    ).catch(() => {});

    // Build the API payload — strip transient UI flags and prepend system prompt.
    const apiMessages: ChatMessage[] = [
      { role: "system", content: persona.systemPrompt },
      ...nextMessages.map((m) => ({ role: m.role, content: m.content })),
    ];

    try {
      const reply = await chatComplete(apiMessages, { maxTokens: 240 });
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: reply.trim() },
      ]);
    } catch (err) {
      if (__DEV__) console.warn("[freechat] chatComplete failed", err);
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: ERROR_FALLBACK, error: true },
      ]);
    } finally {
      setSending(false);
    }
  };

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------

  return (
    <SafeAreaView style={styles.safe} edges={["top", "bottom"]}>
      <StatusBar style="dark" />

      {/* Header */}
      <View style={styles.header}>
        <Pressable
          onPress={() => router.back()}
          style={styles.backBtn}
          hitSlop={8}
        >
          <Text style={styles.backText}>← Geri</Text>
        </Pressable>
        <Text style={styles.title}>Sohbet</Text>
        <Pressable onPress={handleNewSession} style={styles.newBtn} hitSlop={8}>
          <Text style={styles.newBtnText}>Yeni</Text>
        </Pressable>
      </View>

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        keyboardVerticalOffset={Platform.OS === "ios" ? 0 : 0}
      >
        {/* Persona selector card (also doubles as chat header per RoleplayChat style) */}
        <Pressable
          style={styles.personaCard}
          onPress={() => setPickerOpen(true)}
        >
          <View style={styles.personaAvatar}>
            <Text style={styles.personaEmoji}>{persona.emoji}</Text>
          </View>
          <View style={styles.personaText}>
            <Text style={styles.personaName}>{persona.label}</Text>
            <Text style={styles.personaSetting}>{persona.setting}</Text>
          </View>
          <View style={styles.personaCta}>
            <View style={styles.onlineDot} />
            <Text style={styles.personaSwap}>Değiştir ›</Text>
          </View>
        </Pressable>

        {/* Daily-count chip */}
        <View style={styles.counterRow}>
          <Text
            style={[
              styles.counterText,
              atLimit && styles.counterTextLimit,
            ]}
          >
            {atLimit
              ? `Bugün için sınıra ulaştın (${dailyCount}/${DAILY_LIMIT})`
              : `Bugünkü mesaj: ${dailyCount}/${DAILY_LIMIT}`}
          </Text>
        </View>

        {/* Chat scroll */}
        <ScrollView
          ref={scrollRef}
          style={styles.chatScroll}
          contentContainerStyle={styles.chatContent}
          showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
        >
          {messages.map((msg, i) => (
            <ChatBubble key={i} message={msg} />
          ))}

          {sending && (
            <View style={[bubbleStyles.row, bubbleStyles.rowNpc]}>
              <View
                style={[
                  bubbleStyles.bubble,
                  bubbleStyles.bubbleNpc,
                  bubbleStyles.typingBubble,
                ]}
              >
                <ActivityIndicator
                  color={tokens.text.onSecondary}
                  size="small"
                />
                <Text style={bubbleStyles.typingText}>yazıyor…</Text>
              </View>
            </View>
          )}
        </ScrollView>

        {/* Input bar OR paywall CTA */}
        {atLimit ? (
          <View style={styles.paywallBar}>
            <Text style={styles.paywallText}>
              Sınırsız sohbet için Premium'a geç.
            </Text>
            <Pressable
              style={styles.paywallBtn}
              onPress={() => router.push("/paywall" as never)}
            >
              <Text style={styles.paywallBtnText}>Premium'a geç →</Text>
            </Pressable>
          </View>
        ) : (
          <View style={styles.inputBar}>
            <View style={styles.inputRow}>
              <Pressable
                style={styles.micBtn}
                onPress={() =>
                  Alert.alert(
                    "Yakında",
                    "Sesli mesaj özelliği çok yakında geliyor 🎤",
                  )
                }
                hitSlop={6}
              >
                <Text style={styles.micText}>🎤</Text>
              </Pressable>
              <TextInput
                style={styles.input}
                value={input}
                onChangeText={setInput}
                placeholder="İngilizce yaz..."
                placeholderTextColor={tokens.text.tertiary}
                editable={!sending}
                multiline
                autoCapitalize="sentences"
                returnKeyType="send"
                blurOnSubmit={false}
                onSubmitEditing={sendMessage}
              />
              <Pressable
                style={[
                  styles.sendBtn,
                  (!input.trim() || sending) && styles.sendBtnDisabled,
                ]}
                onPress={sendMessage}
                disabled={!input.trim() || sending}
                hitSlop={6}
              >
                <Text style={styles.sendBtnText}>↑</Text>
              </Pressable>
            </View>
          </View>
        )}
      </KeyboardAvoidingView>

      {/* Persona picker modal */}
      <Modal
        visible={pickerOpen}
        animationType="slide"
        transparent
        onRequestClose={() => setPickerOpen(false)}
      >
        <Pressable
          style={modalStyles.backdrop}
          onPress={() => setPickerOpen(false)}
        >
          <Pressable style={modalStyles.sheet} onPress={() => {}}>
            <View style={modalStyles.handle} />
            <Text style={modalStyles.title}>Konuşma partnerini seç</Text>
            <Text style={modalStyles.subtitle}>
              Her partner farklı bir senaryoda sohbet eder
            </Text>
            <View style={modalStyles.list}>
              {PERSONAS.map((p) => {
                const active = p.id === personaId;
                return (
                  <Pressable
                    key={p.id}
                    style={[
                      modalStyles.row,
                      active && modalStyles.rowActive,
                    ]}
                    onPress={() => handlePersonaSelect(p.id)}
                  >
                    <Text style={modalStyles.rowEmoji}>{p.emoji}</Text>
                    <View style={modalStyles.rowText}>
                      <Text style={modalStyles.rowLabel}>{p.label}</Text>
                      <Text style={modalStyles.rowSetting}>{p.setting}</Text>
                    </View>
                    {active && (
                      <Text style={modalStyles.rowCheck}>✓</Text>
                    )}
                  </Pressable>
                );
              })}
            </View>
            <Pressable
              style={modalStyles.closeBtn}
              onPress={() => setPickerOpen(false)}
            >
              <Text style={modalStyles.closeText}>Kapat</Text>
            </Pressable>
          </Pressable>
        </Pressable>
      </Modal>
    </SafeAreaView>
  );
}

// ---------------------------------------------------------------------------
// Chat bubble — tap to replay via TTS (only English / assistant messages
// auto-use en-US, user messages get en-US too since user is practicing English).
// ---------------------------------------------------------------------------

function ChatBubble({ message }: { message: UiMessage }) {
  const isUser = message.role === "user";
  const isError = message.error === true;

  return (
    <View
      style={[
        bubbleStyles.row,
        isUser ? bubbleStyles.rowUser : bubbleStyles.rowNpc,
      ]}
    >
      <Pressable
        onPress={() => speak(message.content, { lang: isError ? "tr-TR" : "en-US" })}
        style={[
          bubbleStyles.bubble,
          isUser
            ? bubbleStyles.bubbleUser
            : isError
              ? bubbleStyles.bubbleError
              : bubbleStyles.bubbleNpc,
        ]}
      >
        <Text
          style={[
            bubbleStyles.text,
            isUser
              ? bubbleStyles.textUser
              : isError
                ? bubbleStyles.textError
                : bubbleStyles.textNpc,
          ]}
        >
          {message.content}
          {!isUser && !isError ? " 🔊" : ""}
        </Text>
      </Pressable>
    </View>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: tokens.bg.app },
  flex: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    height: 56,
  },
  backBtn: { width: 70 },
  backText: { color: tokens.text.secondary, fontSize: 15 },
  title: {
    fontSize: 20,
    fontWeight: tokens.weight.extrabold,
    color: tokens.text.primary,
  },
  newBtn: {
    width: 70,
    alignItems: "flex-end",
  },
  newBtnText: {
    color: tokens.brand.tertiary,
    fontSize: 14,
    fontWeight: tokens.weight.bold,
  },
  personaCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: tokens.bg.surfaceContainer,
    borderRadius: tokens.radius.base,
    borderWidth: 1,
    borderColor: tokens.border.light,
  },
  personaAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.brand.secondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: tokens.brand.tertiary,
  },
  personaEmoji: {
    fontSize: 22,
  },
  personaText: { flex: 1 },
  personaName: {
    fontSize: 16,
    fontWeight: tokens.weight.bold,
    color: tokens.text.primary,
  },
  personaSetting: {
    fontSize: 12,
    color: tokens.text.secondary,
  },
  personaCta: {
    alignItems: "flex-end",
    gap: 4,
  },
  onlineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: tokens.brand.tertiary,
  },
  personaSwap: {
    fontSize: 11,
    color: tokens.brand.tertiary,
    fontWeight: tokens.weight.semibold,
  },
  counterRow: {
    alignItems: "center",
    paddingBottom: 6,
  },
  counterText: {
    fontSize: 11,
    color: tokens.text.tertiary,
    fontWeight: tokens.weight.semibold,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  counterTextLimit: {
    color: tokens.semantic.error,
  },
  chatScroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  chatContent: {
    paddingVertical: 12,
    gap: 10,
  },
  inputBar: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: tokens.border.light,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  micBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.bg.surfaceContainerHigh,
    alignItems: "center",
    justifyContent: "center",
  },
  micText: {
    fontSize: 20,
  },
  input: {
    flex: 1,
    backgroundColor: tokens.bg.surfaceContainer,
    borderWidth: 1,
    borderColor: tokens.border.light,
    borderRadius: tokens.radius.full,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: tokens.text.primary,
    maxHeight: 100,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: tokens.brand.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  sendBtnDisabled: {
    opacity: 0.4,
  },
  sendBtnText: {
    color: tokens.text.onPrimary,
    fontSize: 22,
    fontWeight: tokens.weight.black,
  },
  paywallBar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: tokens.border.light,
    gap: 8,
  },
  paywallText: {
    fontSize: 13,
    color: tokens.text.secondary,
    textAlign: "center",
  },
  paywallBtn: {
    backgroundColor: tokens.brand.primary,
    paddingVertical: 14,
    borderRadius: tokens.radius.full,
    alignItems: "center",
  },
  paywallBtnText: {
    color: tokens.text.onPrimary,
    fontSize: 15,
    fontWeight: tokens.weight.extrabold,
    letterSpacing: 0.3,
  },
});

const bubbleStyles = StyleSheet.create({
  row: {
    flexDirection: "column",
    maxWidth: "85%",
  },
  rowNpc: {
    alignSelf: "flex-start",
    alignItems: "flex-start",
  },
  rowUser: {
    alignSelf: "flex-end",
    alignItems: "flex-end",
  },
  bubble: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
  },
  bubbleNpc: {
    backgroundColor: tokens.brand.secondary,
    borderBottomLeftRadius: 4,
  },
  bubbleUser: {
    backgroundColor: tokens.brand.primary,
    borderBottomRightRadius: 4,
  },
  bubbleError: {
    backgroundColor: tokens.semantic.errorContainer,
    borderBottomLeftRadius: 4,
  },
  text: {
    fontSize: 15,
    lineHeight: 21,
  },
  textNpc: {
    color: tokens.text.onSecondary,
  },
  textUser: {
    color: tokens.text.onPrimary,
  },
  textError: {
    color: tokens.semantic.onErrorContainer,
  },
  typingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  typingText: {
    color: tokens.text.onSecondary,
    fontSize: 13,
    fontStyle: "italic",
  },
});

const modalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: tokens.bg.app,
    borderTopLeftRadius: tokens.radius.lg,
    borderTopRightRadius: tokens.radius.lg,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: tokens.border.outlineVariant,
    alignSelf: "center",
    marginBottom: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: tokens.weight.extrabold,
    color: tokens.text.primary,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 13,
    color: tokens.text.secondary,
    textAlign: "center",
    marginTop: 4,
    marginBottom: 16,
  },
  list: {
    gap: 8,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: tokens.radius.base,
    backgroundColor: tokens.bg.surfaceContainer,
    borderWidth: 2,
    borderColor: "transparent",
  },
  rowActive: {
    borderColor: tokens.brand.tertiary,
    backgroundColor: tokens.brand.tertiarySoft,
  },
  rowEmoji: {
    fontSize: 28,
  },
  rowText: { flex: 1 },
  rowLabel: {
    fontSize: 15,
    fontWeight: tokens.weight.bold,
    color: tokens.text.primary,
  },
  rowSetting: {
    fontSize: 12,
    color: tokens.text.secondary,
    marginTop: 2,
  },
  rowCheck: {
    color: tokens.brand.tertiary,
    fontSize: 22,
    fontWeight: tokens.weight.black,
  },
  closeBtn: {
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: tokens.radius.full,
    backgroundColor: tokens.bg.surfaceContainerHigh,
    alignItems: "center",
  },
  closeText: {
    fontSize: 15,
    fontWeight: tokens.weight.bold,
    color: tokens.text.primary,
  },
});
