export const FREE_CHAT_OPENERS: Record<string, string> = {
  "daily.howsday": "hey :) how was your day?",
  "daily.morning": "morning! what's the first thing you did today?",
  "work.project": "what's the project you've been spending the most time on?",
  "work.meeting": "how many meetings did you have today? be honest",
  "weekend.plan": "any plans for the weekend?",
  "weekend.lastdid": "what's the best thing you did last weekend?",
  "food.lastate": "what's the last thing you ate?",
  "food.favorite": "what's your go-to comfort food?",
  "social.lastfriend": "when did you last see a close friend in person?",
  "social.newpeople": "are you good at meeting new people, or does it stress you out?",
  "feel.mood": "how are you actually feeling today? not the polite answer",
  "tool.emergency": "Turn a Turkish real-life need into natural English options.",
  "tool.custom-scenario": "Build a short English roleplay from the user's real-life situation.",
};
