// Lafla — Hand-curated CMU Pronouncing Dictionary subset.
//
// Why a subset? The full CMUDict is ~120k entries / ~3 MB. For a Turkish
// learner app we only need:
//   1. Every word that appears in data/pronunciation-drills.ts (so the
//      phoneme grader can ALWAYS score drill targets accurately).
//   2. A few hundred of the highest-frequency English words so the grader
//      handles natural conversation transcripts without falling back to
//      g2p heuristics on common items.
//
// Format: lowercase word -> ARPAbet phoneme array (no stress markers; we
// strip them because Turkish learners shouldn't be punished for stress
// placement at the phoneme-band level — stress is graded elsewhere).
//
// ARPAbet symbol set used:
//   Vowels:     AA AE AH AO AW AY EH ER EY IH IY OW OY UH UW
//   Consonants: B CH D DH F G HH JH K L M N NG P R S SH T TH V W Y Z ZH
//
// The IPA mapping below uses GA (General American) values; this matches
// the IPA already shown in data/pronunciation-drills.ts.

export const ARPABET_TO_IPA: Readonly<Record<string, string>> = {
  // Vowels
  AA: "ɑ", // father
  AE: "æ", // cat
  AH: "ʌ", // cut / about (schwa folded into AH for simplicity)
  AO: "ɔ", // thought
  AW: "aʊ", // mouth
  AY: "aɪ", // price
  EH: "ɛ", // bed
  ER: "ɜr", // bird
  EY: "eɪ", // face
  IH: "ɪ", // ship
  IY: "i", // sheep
  OW: "oʊ", // boat
  OY: "ɔɪ", // boy
  UH: "ʊ", // foot
  UW: "u", // boot
  // Consonants
  B: "b",
  CH: "tʃ",
  D: "d",
  DH: "ð", // this
  F: "f",
  G: "ɡ",
  HH: "h",
  JH: "dʒ",
  K: "k",
  L: "l",
  M: "m",
  N: "n",
  NG: "ŋ", // sing
  P: "p",
  R: "r",
  S: "s",
  SH: "ʃ",
  T: "t",
  TH: "θ", // think
  V: "v",
  W: "w",
  Y: "j",
  Z: "z",
  ZH: "ʒ", // measure
};

// Convenience set so g2p can validate symbols at runtime.
export const ARPABET_SYMBOLS: ReadonlySet<string> = new Set(
  Object.keys(ARPABET_TO_IPA),
);

// ============================================================
// Dictionary entries
// ============================================================
// Organized roughly by frequency / drill coverage. Entries are
// alphabetized within blocks for easier human auditing.
//
// All keys are lowercase. Apostrophes preserved (e.g. "he's", "won't").
// Multi-pronunciation words use the most common GA variant.

export const CMUDICT_MINI: Readonly<Record<string, readonly string[]>> = {
  // ---- Drill 1: /θ/ (th-think) ----
  think: ["TH", "IH", "NG", "K"],
  thank: ["TH", "AE", "NG", "K"],
  thing: ["TH", "IH", "NG"],
  three: ["TH", "R", "IY"],
  thirty: ["TH", "ER", "T", "IY"],
  thousand: ["TH", "AW", "Z", "AH", "N", "D"],
  thirsty: ["TH", "ER", "S", "T", "IY"],
  throw: ["TH", "R", "OW"],
  thick: ["TH", "IH", "K"],
  thin: ["TH", "IH", "N"],
  thunder: ["TH", "AH", "N", "D", "ER"],
  theater: ["TH", "IY", "AH", "T", "ER"],
  theme: ["TH", "IY", "M"],
  thread: ["TH", "R", "EH", "D"],
  thorough: ["TH", "ER", "OW"],
  math: ["M", "AE", "TH"],
  bath: ["B", "AE", "TH"],
  mouth: ["M", "AW", "TH"],
  tooth: ["T", "UW", "TH"],
  birthday: ["B", "ER", "TH", "D", "EY"],
  thomas: ["T", "AA", "M", "AH", "S"],
  things: ["TH", "IH", "NG", "Z"],
  thirteen: ["TH", "ER", "T", "IY", "N"],
  third: ["TH", "ER", "D"],
  thursday: ["TH", "ER", "Z", "D", "EY"],
  through: ["TH", "R", "UW"],
  thoughtful: ["TH", "AO", "T", "F", "AH", "L"],
  thought: ["TH", "AO", "T"],
  thumb: ["TH", "AH", "M"],
  thigh: ["TH", "AY"],
  path: ["P", "AE", "TH"],
  thaw: ["TH", "AO"],
  thrilling: ["TH", "R", "IH", "L", "IH", "NG"],
  toothbrush: ["T", "UW", "TH", "B", "R", "AH", "SH"],
  tough: ["T", "AH", "F"],

  // ---- Drill 1 minimal pairs (S-side) ----
  sink: ["S", "IH", "NG", "K"],
  sick: ["S", "IH", "K"],
  sum: ["S", "AH", "M"],
  sigh: ["S", "AY"],
  pass: ["P", "AE", "S"],
  mouse: ["M", "AW", "S"],
  saw: ["S", "AO"],
  passed: ["P", "AE", "S", "T"],

  // ---- Drill 2: /ð/ (th-this) ----
  this: ["DH", "IH", "S"],
  that: ["DH", "AE", "T"],
  the: ["DH", "AH"],
  they: ["DH", "EY"],
  there: ["DH", "EH", "R"],
  these: ["DH", "IY", "Z"],
  those: ["DH", "OW", "Z"],
  than: ["DH", "AE", "N"],
  then: ["DH", "EH", "N"],
  them: ["DH", "EH", "M"],
  though: ["DH", "OW"],
  father: ["F", "AA", "DH", "ER"],
  mother: ["M", "AH", "DH", "ER"],
  brother: ["B", "R", "AH", "DH", "ER"],
  brothers: ["B", "R", "AH", "DH", "ER", "Z"],
  other: ["AH", "DH", "ER"],
  weather: ["W", "EH", "DH", "ER"],
  together: ["T", "AH", "G", "EH", "DH", "ER"],
  rather: ["R", "AE", "DH", "ER"],
  breathe: ["B", "R", "IY", "DH"],
  smooth: ["S", "M", "UW", "DH"],
  smoother: ["S", "M", "UW", "DH", "ER"],
  their: ["DH", "EH", "R"],
  theirs: ["DH", "EH", "R", "Z"],
  although: ["AO", "L", "DH", "OW"],
  clothe: ["K", "L", "OW", "DH"],
  writhe: ["R", "AY", "DH"],
  lather: ["L", "AE", "DH", "ER"],

  // ---- Drill 2 minimal pairs (Z/D-side) ----
  day: ["D", "EY"],
  den: ["D", "EH", "N"],
  dough: ["D", "OW"],
  breeze: ["B", "R", "IY", "Z"],
  close: ["K", "L", "OW", "Z"], // verb sense; "K L OW S" for adj
  rise: ["R", "AY", "Z"],
  ladder: ["L", "AE", "D", "ER"],

  // ---- Drill 3: /ɪ/ vs /iː/ (ship-sheep) ----
  ship: ["SH", "IH", "P"],
  sheep: ["SH", "IY", "P"],
  fit: ["F", "IH", "T"],
  feet: ["F", "IY", "T"],
  live: ["L", "IH", "V"],
  leave: ["L", "IY", "V"],
  bit: ["B", "IH", "T"],
  beat: ["B", "IY", "T"],
  sit: ["S", "IH", "T"],
  seat: ["S", "IY", "T"],
  rich: ["R", "IH", "CH"],
  reach: ["R", "IY", "CH"],
  his: ["HH", "IH", "Z"],
  "he's": ["HH", "IY", "Z"],
  fill: ["F", "IH", "L"],
  feel: ["F", "IY", "L"],
  still: ["S", "T", "IH", "L"],
  steel: ["S", "T", "IY", "L"],
  chip: ["CH", "IH", "P"],
  cheap: ["CH", "IY", "P"],
  chips: ["CH", "IH", "P", "S"],
  crispy: ["K", "R", "IH", "S", "P", "IY"],
  shelf: ["SH", "EH", "L", "F"],
  meat: ["M", "IY", "T"],
  eat: ["IY", "T"],
  ate: ["EY", "T"],
  deck: ["D", "EH", "K"],

  // ---- Drill 4: /ʌ/ vs /æ/ (cut-cat) ----
  cut: ["K", "AH", "T"],
  cat: ["K", "AE", "T"],
  but: ["B", "AH", "T"],
  bat: ["B", "AE", "T"],
  fun: ["F", "AH", "N"],
  fan: ["F", "AE", "N"],
  luck: ["L", "AH", "K"],
  lack: ["L", "AE", "K"],
  hut: ["HH", "AH", "T"],
  hat: ["HH", "AE", "T"],
  sam: ["S", "AE", "M"],
  rub: ["R", "AH", "B"],
  rabbit: ["R", "AE", "B", "AH", "T"],
  must: ["M", "AH", "S", "T"],
  mast: ["M", "AE", "S", "T"],
  uncle: ["AH", "NG", "K", "AH", "L"],
  ankle: ["AE", "NG", "K", "AH", "L"],
  stuck: ["S", "T", "AH", "K"],
  stack: ["S", "T", "AE", "K"],
  hurt: ["HH", "ER", "T"],
  loud: ["L", "AW", "D"],
  cash: ["K", "AE", "SH"],
  half: ["HH", "AE", "F"],
  rug: ["R", "AH", "G"],
  ran: ["R", "AE", "N"],
  wear: ["W", "EH", "R"],
  black: ["B", "L", "AE", "K"],

  // ---- Drill 5: /æ/ vs /ɛ/ (bad-bed) ----
  bed: ["B", "EH", "D"],
  bad: ["B", "AE", "D"],
  sat: ["S", "AE", "T"],
  set: ["S", "EH", "T"],
  man: ["M", "AE", "N"],
  men: ["M", "EH", "N"],
  pan: ["P", "AE", "N"],
  pen: ["P", "EH", "N"],
  and: ["AE", "N", "D"],
  end: ["EH", "N", "D"],
  had: ["HH", "AE", "D"],
  head: ["HH", "EH", "D"],
  axe: ["AE", "K", "S"],
  x: ["EH", "K", "S"],
  ten: ["T", "EH", "N"],
  happy: ["HH", "AE", "P", "IY"],
  heavy: ["HH", "EH", "V", "IY"],
  track: ["T", "R", "AE", "K"],
  trek: ["T", "R", "EH", "K"],
  pad: ["P", "AE", "D"],
  bags: ["B", "AE", "G", "Z"],
  healthy: ["HH", "EH", "L", "TH", "IY"],
  lunch: ["L", "AH", "N", "CH"],
  mat: ["M", "AE", "T"],
  next: ["N", "EH", "K", "S", "T"],

  // ---- Drill 6: /ɒ/-/ɔː/-/oʊ/ (hot-caught-coat) ----
  hot: ["HH", "AA", "T"],
  stop: ["S", "T", "AA", "P"],
  lot: ["L", "AA", "T"],
  box: ["B", "AA", "K", "S"],
  clock: ["K", "L", "AA", "K"],
  caught: ["K", "AO", "T"],
  bought: ["B", "AO", "T"],
  talk: ["T", "AO", "K"],
  wall: ["W", "AO", "L"],
  law: ["L", "AO"],
  ball: ["B", "AO", "L"],
  coat: ["K", "OW", "T"],
  boat: ["B", "OW", "T"],
  phone: ["F", "OW", "N"],
  road: ["R", "OW", "D"],
  go: ["G", "OW"],
  know: ["N", "OW"],
  show: ["SH", "OW"],
  home: ["HH", "OW", "M"],
  cot: ["K", "AA", "T"],
  low: ["L", "OW"],
  want: ["W", "AA", "N", "T"],
  "won't": ["W", "OW", "N", "T"],
  cold: ["K", "OW", "L", "D"],
  driving: ["D", "R", "AY", "V", "IH", "NG"],
  hall: ["HH", "AO", "L"],
  fall: ["F", "AO", "L"],
  drink: ["D", "R", "IH", "NG", "K"],

  // ---- Drill 7: /v/ vs /w/ (vest-west) ----
  very: ["V", "EH", "R", "IY"],
  wary: ["W", "EH", "R", "IY"],
  vine: ["V", "AY", "N"],
  wine: ["W", "AY", "N"],
  vest: ["V", "EH", "S", "T"],
  west: ["W", "EH", "S", "T"],
  vet: ["V", "EH", "T"],
  wet: ["W", "EH", "T"],
  veil: ["V", "EY", "L"],
  whale: ["W", "EY", "L"],
  vault: ["V", "AO", "L", "T"],
  victory: ["V", "IH", "K", "T", "ER", "IY"],
  winter: ["W", "IH", "N", "T", "ER"],
  village: ["V", "IH", "L", "IH", "JH"],
  window: ["W", "IH", "N", "D", "OW"],
  voice: ["V", "OY", "S"],
  water: ["W", "AO", "T", "ER"],
  value: ["V", "AE", "L", "Y", "UW"],
  vivian: ["V", "IH", "V", "IY", "AH", "N"],
  velvet: ["V", "EH", "L", "V", "AH", "T"],
  white: ["W", "AY", "T"],
  vinegar: ["V", "IH", "N", "AH", "G", "ER"],
  watched: ["W", "AA", "CH", "T"],
  western: ["W", "EH", "S", "T", "ER", "N"],
  warm: ["W", "AO", "R", "M"],
  warned: ["W", "AO", "R", "N", "D"],
  wild: ["W", "AY", "L", "D"],
  vail: ["V", "EY", "L"],
  wail: ["W", "EY", "L"],
  verse: ["V", "ER", "S"],
  worse: ["W", "ER", "S"],
  vow: ["V", "AW"],
  wow: ["W", "AW"],

  // ---- Drill 8: voicing finals (tab-tap) ----
  tab: ["T", "AE", "B"],
  tap: ["T", "AE", "P"],
  job: ["JH", "AA", "B"],
  rob: ["R", "AA", "B"],
  club: ["K", "L", "AH", "B"],
  cab: ["K", "AE", "B"],
  cap: ["K", "AE", "P"],
  lab: ["L", "AE", "B"],
  lap: ["L", "AE", "P"],
  mob: ["M", "AA", "B"],
  mop: ["M", "AA", "P"],
  pub: ["P", "AH", "B"],
  pup: ["P", "AH", "P"],
  rib: ["R", "IH", "B"],
  rip: ["R", "IH", "P"],
  robe: ["R", "OW", "B"],
  rope: ["R", "OW", "P"],
  globe: ["G", "L", "OW", "B"],
  describe: ["D", "IH", "S", "K", "R", "AY", "B"],
  absorb: ["AH", "B", "Z", "AO", "R", "B"],
  cub: ["K", "AH", "B"],
  cup: ["K", "AH", "P"],
  plate: ["P", "L", "EY", "T"],
  pull: ["P", "UH", "L"],
  pay: ["P", "EY"],
  bill: ["B", "IH", "L"],
  wore: ["W", "AO", "R"],

  // ---- Drill 9: flap T (water → wadder) ----
  better: ["B", "EH", "T", "ER"],
  letter: ["L", "EH", "T", "ER"],
  butter: ["B", "AH", "T", "ER"],
  city: ["S", "IH", "T", "IY"],
  pretty: ["P", "R", "IH", "T", "IY"],
  party: ["P", "AA", "R", "T", "IY"],
  italy: ["IH", "T", "AH", "L", "IY"],
  matter: ["M", "AE", "T", "ER"],
  data: ["D", "EY", "T", "AH"],
  later: ["L", "EY", "T", "ER"],
  writer: ["R", "AY", "T", "ER"],
  metal: ["M", "EH", "T", "AH", "L"],
  bottle: ["B", "AA", "T", "AH", "L"],
  little: ["L", "IH", "T", "AH", "L"],
  atom: ["AE", "T", "AH", "M"],
  photo: ["F", "OW", "T", "OW"],
  auto: ["AO", "T", "OW"],
  saturday: ["S", "AE", "T", "ER", "D", "EY"],
  rider: ["R", "AY", "D", "ER"],
  latter: ["L", "AE", "T", "ER"],
  medal: ["M", "EH", "D", "AH", "L"],
  adam: ["AE", "D", "AH", "M"],
  wrote: ["R", "OW", "T"],
  store: ["S", "T", "AO", "R"],
  people: ["P", "IY", "P", "AH", "L"],

  // ---- Drill 10: light vs dark L ----
  leaf: ["L", "IY", "F"],
  light: ["L", "AY", "T"],
  love: ["L", "AH", "V"],
  lemon: ["L", "EH", "M", "AH", "N"],
  like: ["L", "AY", "K"],
  lucky: ["L", "AH", "K", "IY"],
  lonely: ["L", "OW", "N", "L", "IY"],
  all: ["AO", "L"],
  cool: ["K", "UW", "L"],
  school: ["S", "K", "UW", "L"],
  milk: ["M", "IH", "L", "K"],
  tall: ["T", "AO", "L"],
  well: ["W", "EH", "L"],
  table: ["T", "EY", "B", "AH", "L"],
  apple: ["AE", "P", "AH", "L"],
  global: ["G", "L", "OW", "B", "AH", "L"],
  lit: ["L", "IH", "T"],
  till: ["T", "IH", "L"],
  pal: ["P", "AE", "L"],
  full: ["F", "UH", "L"],
  leaving: ["L", "IY", "V", "IH", "NG"],
  pals: ["P", "AE", "L", "Z"],
  kids: ["K", "IH", "D", "Z"],
  slippery: ["S", "L", "IH", "P", "ER", "IY"],
  floor: ["F", "L", "AO", "R"],

  // ---- Drill 11: /ŋ/ (-ing) ----
  sing: ["S", "IH", "NG"],
  king: ["K", "IH", "NG"],
  ring: ["R", "IH", "NG"],
  long: ["L", "AO", "NG"],
  young: ["Y", "AH", "NG"],
  song: ["S", "AO", "NG"],
  wrong: ["R", "AO", "NG"],
  strong: ["S", "T", "R", "AO", "NG"],
  morning: ["M", "AO", "R", "N", "IH", "NG"],
  evening: ["IY", "V", "N", "IH", "NG"],
  running: ["R", "AH", "N", "IH", "NG"],
  going: ["G", "OW", "IH", "NG"],
  swimming: ["S", "W", "IH", "M", "IH", "NG"],
  amazing: ["AH", "M", "EY", "Z", "IH", "NG"],
  shopping: ["SH", "AA", "P", "IH", "NG"],
  anything: ["EH", "N", "IY", "TH", "IH", "NG"],
  nothing: ["N", "AH", "TH", "IH", "NG"],
  everything: ["EH", "V", "R", "IY", "TH", "IH", "NG"],
  tongue: ["T", "AH", "NG"],
  sin: ["S", "IH", "N"],
  ban: ["B", "AE", "N"],
  bang: ["B", "AE", "NG"],
  rang: ["R", "AE", "NG"],
  ton: ["T", "AH", "N"],
  win: ["W", "IH", "N"],
  wing: ["W", "IH", "NG"],
  singing: ["S", "IH", "NG", "IH", "NG"],
  bringing: ["B", "R", "IH", "NG", "IH", "NG"],
  thinking: ["TH", "IH", "NG", "K", "IH", "NG"],
  working: ["W", "ER", "K", "IH", "NG"],
  except: ["IH", "K", "S", "EH", "P", "T"],

  // ---- Drill 12: word-stress shifts ----
  record: ["R", "EH", "K", "ER", "D"], // noun (one variant)
  present: ["P", "R", "EH", "Z", "AH", "N", "T"],
  object: ["AA", "B", "JH", "EH", "K", "T"],
  increase: ["IH", "N", "K", "R", "IY", "S"],
  import: ["IH", "M", "P", "AO", "R", "T"],
  contract: ["K", "AA", "N", "T", "R", "AE", "K", "T"],
  year: ["Y", "IH", "R"],
  meeting: ["M", "IY", "T", "IH", "NG"],
  abroad: ["AH", "B", "R", "AO", "D"],
  work: ["W", "ER", "K"],

  // ---- Drill 13/14: sentence stress, schwa, contractions ----
  bread: ["B", "R", "EH", "D"],
  "can't": ["K", "AE", "N", "T"],
  come: ["K", "AH", "M"],
  because: ["B", "IH", "K", "AO", "Z"],
  tired: ["T", "AY", "ER", "D"],
  coffee: ["K", "AO", "F", "IY"],
  buy: ["B", "AY"],
  new: ["N", "UW"],
  car: ["K", "AA", "R"],
  week: ["W", "IY", "K"],
  "should've": ["SH", "UH", "D", "AH", "V"],
  told: ["T", "OW", "L", "D"],
  before: ["B", "IH", "F", "AO", "R"],
  help: ["HH", "EH", "L", "P"],
  stay: ["S", "T", "EY"],
  can: ["K", "AE", "N"],

  // ---- Drill 15: reductions / casual speech ----
  wanna: ["W", "AA", "N", "AH"],
  gonna: ["G", "AO", "N", "AH"],
  gotta: ["G", "AA", "T", "AH"],
  didja: ["D", "IH", "JH", "AH"],
  whaddya: ["W", "AH", "T", "AH", "Y", "AH"],
  lemme: ["L", "EH", "M", "IY"],
  gimme: ["G", "IH", "M", "IY"],
  kinda: ["K", "AY", "N", "D", "AH"],
  sorta: ["S", "AO", "R", "T", "AH"],
  outta: ["AW", "T", "AH"],
  shoulda: ["SH", "UH", "D", "AH"],
  coulda: ["K", "UH", "D", "AH"],
  woulda: ["W", "UH", "D", "AH"],
  musta: ["M", "AH", "S", "T", "AH"],
  ya: ["Y", "AH"],
  cuz: ["K", "AH", "Z"],
  dunno: ["D", "AH", "N", "OW"],
  betcha: ["B", "EH", "CH", "AH"],
  tellya: ["T", "EH", "L", "Y", "AH"],
  finish: ["F", "IH", "N", "IH", "SH"],
  first: ["F", "ER", "S", "T"],
  see: ["S", "IY"],
  minute: ["M", "IH", "N", "AH", "T"],
  sooner: ["S", "UW", "N", "ER"],
  said: ["S", "EH", "D"],
  gone: ["G", "AO", "N"],

  // ---- Intonation drill sentences ----
  ready: ["R", "EH", "D", "IY"],
  yes: ["Y", "EH", "S"],
  where: ["W", "EH", "R"],
  do: ["D", "UW"],
  you: ["Y", "UW"],
  istanbul: ["IH", "S", "T", "AH", "N", "B", "UH", "L"],
  did: ["D", "IH", "D"],
  not: ["N", "AA", "T"],
  yet: ["Y", "EH", "T"],
  beautiful: ["B", "Y", "UW", "T", "AH", "F", "AH", "L"],
  "isn't": ["IH", "Z", "AH", "N", "T"],
  it: ["IH", "T"],
  what: ["W", "AH", "T"],
  your: ["Y", "AO", "R"],
  name: ["N", "EY", "M"],
  is: ["IH", "Z"],
  berk: ["B", "ER", "K"],
  "you're": ["Y", "UH", "R"],
  coming: ["K", "AH", "M", "IH", "NG"],
  right: ["R", "AY", "T"],
  or: ["AO", "R"],
  tea: ["T", "IY"],

  // ============================================================
  // High-frequency English fillers (top 600 lemmas, deduped vs above)
  // ============================================================
  a: ["AH"],
  about: ["AH", "B", "AW", "T"],
  above: ["AH", "B", "AH", "V"],
  across: ["AH", "K", "R", "AO", "S"],
  act: ["AE", "K", "T"],
  add: ["AE", "D"],
  after: ["AE", "F", "T", "ER"],
  again: ["AH", "G", "EH", "N"],
  against: ["AH", "G", "EH", "N", "S", "T"],
  age: ["EY", "JH"],
  ago: ["AH", "G", "OW"],
  agree: ["AH", "G", "R", "IY"],
  air: ["EH", "R"],
  almost: ["AO", "L", "M", "OW", "S", "T"],
  alone: ["AH", "L", "OW", "N"],
  along: ["AH", "L", "AO", "NG"],
  already: ["AO", "L", "R", "EH", "D", "IY"],
  also: ["AO", "L", "S", "OW"],
  always: ["AO", "L", "W", "EY", "Z"],
  am: ["AE", "M"],
  among: ["AH", "M", "AH", "NG"],
  an: ["AE", "N"],
  another: ["AH", "N", "AH", "DH", "ER"],
  answer: ["AE", "N", "S", "ER"],
  any: ["EH", "N", "IY"],
  anyone: ["EH", "N", "IY", "W", "AH", "N"],
  appear: ["AH", "P", "IH", "R"],
  area: ["EH", "R", "IY", "AH"],
  arm: ["AA", "R", "M"],
  around: ["ER", "AW", "N", "D"],
  arrive: ["ER", "AY", "V"],
  art: ["AA", "R", "T"],
  as: ["AE", "Z"],
  ask: ["AE", "S", "K"],
  at: ["AE", "T"],
  away: ["AH", "W", "EY"],
  baby: ["B", "EY", "B", "IY"],
  back: ["B", "AE", "K"],
  bag: ["B", "AE", "G"],
  bank: ["B", "AE", "NG", "K"],
  base: ["B", "EY", "S"],
  be: ["B", "IY"],
  bear: ["B", "EH", "R"],
  become: ["B", "IH", "K", "AH", "M"],
  begin: ["B", "IH", "G", "IH", "N"],
  behind: ["B", "IH", "HH", "AY", "N", "D"],
  believe: ["B", "IH", "L", "IY", "V"],
  best: ["B", "EH", "S", "T"],
  between: ["B", "IH", "T", "W", "IY", "N"],
  big: ["B", "IH", "G"],
  bird: ["B", "ER", "D"],
  blue: ["B", "L", "UW"],
  body: ["B", "AA", "D", "IY"],
  book: ["B", "UH", "K"],
  born: ["B", "AO", "R", "N"],
  both: ["B", "OW", "TH"],
  boy: ["B", "OY"],
  break: ["B", "R", "EY", "K"],
  bring: ["B", "R", "IH", "NG"],
  build: ["B", "IH", "L", "D"],
  business: ["B", "IH", "Z", "N", "AH", "S"],
  by: ["B", "AY"],
  call: ["K", "AO", "L"],
  case: ["K", "EY", "S"],
  catch: ["K", "AE", "CH"],
  cause: ["K", "AO", "Z"],
  center: ["S", "EH", "N", "T", "ER"],
  certain: ["S", "ER", "T", "AH", "N"],
  chair: ["CH", "EH", "R"],
  chance: ["CH", "AE", "N", "S"],
  change: ["CH", "EY", "N", "JH"],
  charge: ["CH", "AA", "R", "JH"],
  check: ["CH", "EH", "K"],
  child: ["CH", "AY", "L", "D"],
  children: ["CH", "IH", "L", "D", "R", "AH", "N"],
  choose: ["CH", "UW", "Z"],
  church: ["CH", "ER", "CH"],
  class: ["K", "L", "AE", "S"],
  clean: ["K", "L", "IY", "N"],
  clear: ["K", "L", "IH", "R"],
  color: ["K", "AH", "L", "ER"],
  company: ["K", "AH", "M", "P", "AH", "N", "IY"],
  consider: ["K", "AH", "N", "S", "IH", "D", "ER"],
  continue: ["K", "AH", "N", "T", "IH", "N", "Y", "UW"],
  cost: ["K", "AO", "S", "T"],
  could: ["K", "UH", "D"],
  country: ["K", "AH", "N", "T", "R", "IY"],
  course: ["K", "AO", "R", "S"],
  cover: ["K", "AH", "V", "ER"],
  create: ["K", "R", "IY", "EY", "T"],
  cry: ["K", "R", "AY"],
  dad: ["D", "AE", "D"],
  dance: ["D", "AE", "N", "S"],
  dark: ["D", "AA", "R", "K"],
  date: ["D", "EY", "T"],
  daughter: ["D", "AO", "T", "ER"],
  dead: ["D", "EH", "D"],
  deal: ["D", "IY", "L"],
  decide: ["D", "IH", "S", "AY", "D"],
  deep: ["D", "IY", "P"],
  describe2: ["D", "IH", "S", "K", "R", "AY", "B"],
  develop: ["D", "IH", "V", "EH", "L", "AH", "P"],
  die: ["D", "AY"],
  different: ["D", "IH", "F", "ER", "AH", "N", "T"],
  difficult: ["D", "IH", "F", "AH", "K", "AH", "L", "T"],
  dinner: ["D", "IH", "N", "ER"],
  doctor: ["D", "AA", "K", "T", "ER"],
  dog: ["D", "AO", "G"],
  door: ["D", "AO", "R"],
  down: ["D", "AW", "N"],
  draw: ["D", "R", "AO"],
  dream: ["D", "R", "IY", "M"],
  dress: ["D", "R", "EH", "S"],
  drive: ["D", "R", "AY", "V"],
  drop: ["D", "R", "AA", "P"],
  during: ["D", "UH", "R", "IH", "NG"],
  each: ["IY", "CH"],
  early: ["ER", "L", "IY"],
  earth: ["ER", "TH"],
  easy: ["IY", "Z", "IY"],
  east: ["IY", "S", "T"],
  edge: ["EH", "JH"],
  effect: ["IH", "F", "EH", "K", "T"],
  eight: ["EY", "T"],
  either: ["IY", "DH", "ER"],
  empty: ["EH", "M", "P", "T", "IY"],
  enough: ["IH", "N", "AH", "F"],
  enter: ["EH", "N", "T", "ER"],
  even: ["IY", "V", "AH", "N"],
  ever: ["EH", "V", "ER"],
  every: ["EH", "V", "R", "IY"],
  example: ["IH", "G", "Z", "AE", "M", "P", "AH", "L"],
  expect: ["IH", "K", "S", "P", "EH", "K", "T"],
  experience: ["IH", "K", "S", "P", "IH", "R", "IY", "AH", "N", "S"],
  explain: ["IH", "K", "S", "P", "L", "EY", "N"],
  eye: ["AY"],
  face: ["F", "EY", "S"],
  fact: ["F", "AE", "K", "T"],
  family: ["F", "AE", "M", "AH", "L", "IY"],
  far: ["F", "AA", "R"],
  fast: ["F", "AE", "S", "T"],
  feed: ["F", "IY", "D"],
  few: ["F", "Y", "UW"],
  field: ["F", "IY", "L", "D"],
  fight: ["F", "AY", "T"],
  figure: ["F", "IH", "G", "Y", "ER"],
  film: ["F", "IH", "L", "M"],
  final: ["F", "AY", "N", "AH", "L"],
  find: ["F", "AY", "N", "D"],
  fine: ["F", "AY", "N"],
  finger: ["F", "IH", "NG", "G", "ER"],
  fire: ["F", "AY", "ER"],
  fish: ["F", "IH", "SH"],
  five: ["F", "AY", "V"],
  fly: ["F", "L", "AY"],
  follow: ["F", "AA", "L", "OW"],
  food: ["F", "UW", "D"],
  foot: ["F", "UH", "T"],
  for: ["F", "AO", "R"],
  force: ["F", "AO", "R", "S"],
  foreign: ["F", "AO", "R", "AH", "N"],
  forest: ["F", "AO", "R", "AH", "S", "T"],
  forget: ["F", "ER", "G", "EH", "T"],
  form: ["F", "AO", "R", "M"],
  four: ["F", "AO", "R"],
  free: ["F", "R", "IY"],
  friend: ["F", "R", "EH", "N", "D"],
  from: ["F", "R", "AH", "M"],
  front: ["F", "R", "AH", "N", "T"],
  game: ["G", "EY", "M"],
  garden: ["G", "AA", "R", "D", "AH", "N"],
  get: ["G", "EH", "T"],
  girl: ["G", "ER", "L"],
  give: ["G", "IH", "V"],
  glass: ["G", "L", "AE", "S"],
  god: ["G", "AA", "D"],
  good: ["G", "UH", "D"],
  govern: ["G", "AH", "V", "ER", "N"],
  grab: ["G", "R", "AE", "B"],
  great: ["G", "R", "EY", "T"],
  green: ["G", "R", "IY", "N"],
  ground: ["G", "R", "AW", "N", "D"],
  group: ["G", "R", "UW", "P"],
  grow: ["G", "R", "OW"],
  guess: ["G", "EH", "S"],
  hair: ["HH", "EH", "R"],
  hand: ["HH", "AE", "N", "D"],
  hang: ["HH", "AE", "NG"],
  happen: ["HH", "AE", "P", "AH", "N"],
  hard: ["HH", "AA", "R", "D"],
  have: ["HH", "AE", "V"],
  he: ["HH", "IY"],
  hear: ["HH", "IH", "R"],
  heart: ["HH", "AA", "R", "T"],
  heat: ["HH", "IY", "T"],
  hello: ["HH", "AH", "L", "OW"],
  her: ["HH", "ER"],
  here: ["HH", "IH", "R"],
  hide: ["HH", "AY", "D"],
  high: ["HH", "AY"],
  him: ["HH", "IH", "M"],
  himself: ["HH", "IH", "M", "S", "EH", "L", "F"],
  hold: ["HH", "OW", "L", "D"],
  hope: ["HH", "OW", "P"],
  hour: ["AW", "ER"],
  house: ["HH", "AW", "S"],
  how: ["HH", "AW"],
  human: ["HH", "Y", "UW", "M", "AH", "N"],
  hundred: ["HH", "AH", "N", "D", "R", "AH", "D"],
  husband: ["HH", "AH", "Z", "B", "AH", "N", "D"],
  i: ["AY"],
  idea: ["AY", "D", "IY", "AH"],
  if: ["IH", "F"],
  imagine: ["IH", "M", "AE", "JH", "AH", "N"],
  important: ["IH", "M", "P", "AO", "R", "T", "AH", "N", "T"],
  in: ["IH", "N"],
  inside: ["IH", "N", "S", "AY", "D"],
  instead: ["IH", "N", "S", "T", "EH", "D"],
  interest: ["IH", "N", "T", "R", "AH", "S", "T"],
  into: ["IH", "N", "T", "UW"],
  involve: ["IH", "N", "V", "AA", "L", "V"],
  "i'd": ["AY", "D"],
  "i'll": ["AY", "L"],
  "i'm": ["AY", "M"],
  "it's": ["IH", "T", "S"],
  its: ["IH", "T", "S"],
  jump: ["JH", "AH", "M", "P"],
  just: ["JH", "AH", "S", "T"],
  keep: ["K", "IY", "P"],
  key: ["K", "IY"],
  kill: ["K", "IH", "L"],
  kind: ["K", "AY", "N", "D"],
  knee: ["N", "IY"],
  land: ["L", "AE", "N", "D"],
  large: ["L", "AA", "R", "JH"],
  last: ["L", "AE", "S", "T"],
  late: ["L", "EY", "T"],
  laugh: ["L", "AE", "F"],
  lay: ["L", "EY"],
  lead: ["L", "IY", "D"],
  learn: ["L", "ER", "N"],
  least: ["L", "IY", "S", "T"],
  left: ["L", "EH", "F", "T"],
  leg: ["L", "EH", "G"],
  less: ["L", "EH", "S"],
  let: ["L", "EH", "T"],
  letme: ["L", "EH", "T", "M", "IY"],
  level: ["L", "EH", "V", "AH", "L"],
  lie: ["L", "AY"],
  life: ["L", "AY", "F"],
  lift: ["L", "IH", "F", "T"],
  line: ["L", "AY", "N"],
  list: ["L", "IH", "S", "T"],
  listen: ["L", "IH", "S", "AH", "N"],
  look: ["L", "UH", "K"],
  lose: ["L", "UW", "Z"],
  loss: ["L", "AO", "S"],
  loud2: ["L", "AW", "D"],
  low2: ["L", "OW"],
  main: ["M", "EY", "N"],
  make: ["M", "EY", "K"],
  many: ["M", "EH", "N", "IY"],
  market: ["M", "AA", "R", "K", "AH", "T"],
  marry: ["M", "EH", "R", "IY"],
  matter2: ["M", "AE", "T", "ER"],
  maybe: ["M", "EY", "B", "IY"],
  me: ["M", "IY"],
  mean: ["M", "IY", "N"],
  meet: ["M", "IY", "T"],
  member: ["M", "EH", "M", "B", "ER"],
  middle: ["M", "IH", "D", "AH", "L"],
  might: ["M", "AY", "T"],
  mile: ["M", "AY", "L"],
  million: ["M", "IH", "L", "Y", "AH", "N"],
  mind: ["M", "AY", "N", "D"],
  miss: ["M", "IH", "S"],
  money: ["M", "AH", "N", "IY"],
  month: ["M", "AH", "N", "TH"],
  more: ["M", "AO", "R"],
  most: ["M", "OW", "S", "T"],
  move: ["M", "UW", "V"],
  much: ["M", "AH", "CH"],
  music: ["M", "Y", "UW", "Z", "IH", "K"],
  my: ["M", "AY"],
  myself: ["M", "AY", "S", "EH", "L", "F"],
  near: ["N", "IH", "R"],
  necessary: ["N", "EH", "S", "AH", "S", "EH", "R", "IY"],
  need: ["N", "IY", "D"],
  never: ["N", "EH", "V", "ER"],
  night: ["N", "AY", "T"],
  nine: ["N", "AY", "N"],
  no: ["N", "OW"],
  none: ["N", "AH", "N"],
  nor: ["N", "AO", "R"],
  north: ["N", "AO", "R", "TH"],
  nose: ["N", "OW", "Z"],
  now: ["N", "AW"],
  number: ["N", "AH", "M", "B", "ER"],
  of: ["AH", "V"],
  off: ["AO", "F"],
  offer: ["AO", "F", "ER"],
  office: ["AO", "F", "AH", "S"],
  often: ["AO", "F", "AH", "N"],
  oil: ["OY", "L"],
  ok: ["OW", "K", "EY"],
  okay: ["OW", "K", "EY"],
  old: ["OW", "L", "D"],
  on: ["AA", "N"],
  once: ["W", "AH", "N", "S"],
  one: ["W", "AH", "N"],
  only: ["OW", "N", "L", "IY"],
  open: ["OW", "P", "AH", "N"],
  opinion: ["AH", "P", "IH", "N", "Y", "AH", "N"],
  order: ["AO", "R", "D", "ER"],
  our: ["AW", "ER"],
  out: ["AW", "T"],
  outside: ["AW", "T", "S", "AY", "D"],
  over: ["OW", "V", "ER"],
  own: ["OW", "N"],
  page: ["P", "EY", "JH"],
  paint: ["P", "EY", "N", "T"],
  paper: ["P", "EY", "P", "ER"],
  parent: ["P", "EH", "R", "AH", "N", "T"],
  park: ["P", "AA", "R", "K"],
  part: ["P", "AA", "R", "T"],
  past: ["P", "AE", "S", "T"],
  peace: ["P", "IY", "S"],
  person: ["P", "ER", "S", "AH", "N"],
  pick: ["P", "IH", "K"],
  picture: ["P", "IH", "K", "CH", "ER"],
  piece: ["P", "IY", "S"],
  place: ["P", "L", "EY", "S"],
  plan: ["P", "L", "AE", "N"],
  play: ["P", "L", "EY"],
  please: ["P", "L", "IY", "Z"],
  point: ["P", "OY", "N", "T"],
  poor: ["P", "UH", "R"],
  power: ["P", "AW", "ER"],
  prepare: ["P", "R", "IH", "P", "EH", "R"],
  price: ["P", "R", "AY", "S"],
  problem: ["P", "R", "AA", "B", "L", "AH", "M"],
  program: ["P", "R", "OW", "G", "R", "AE", "M"],
  prove: ["P", "R", "UW", "V"],
  provide: ["P", "R", "AH", "V", "AY", "D"],
  push: ["P", "UH", "SH"],
  put: ["P", "UH", "T"],
  question: ["K", "W", "EH", "S", "CH", "AH", "N"],
  quick: ["K", "W", "IH", "K"],
  quite: ["K", "W", "AY", "T"],
  rain: ["R", "EY", "N"],
  raise: ["R", "EY", "Z"],
  read: ["R", "IY", "D"],
  real: ["R", "IY", "L"],
  realize: ["R", "IY", "AH", "L", "AY", "Z"],
  really: ["R", "IY", "L", "IY"],
  reason: ["R", "IY", "Z", "AH", "N"],
  receive: ["R", "IH", "S", "IY", "V"],
  red: ["R", "EH", "D"],
  remember: ["R", "IH", "M", "EH", "M", "B", "ER"],
  report: ["R", "IH", "P", "AO", "R", "T"],
  rest: ["R", "EH", "S", "T"],
  return: ["R", "IH", "T", "ER", "N"],
  rich2: ["R", "IH", "CH"],
  room: ["R", "UW", "M"],
  round: ["R", "AW", "N", "D"],
  run: ["R", "AH", "N"],
  safe: ["S", "EY", "F"],
  same: ["S", "EY", "M"],
  save: ["S", "EY", "V"],
  say: ["S", "EY"],
  sea: ["S", "IY"],
  second: ["S", "EH", "K", "AH", "N", "D"],
  seem: ["S", "IY", "M"],
  sell: ["S", "EH", "L"],
  send: ["S", "EH", "N", "D"],
  serve: ["S", "ER", "V"],
  seven: ["S", "EH", "V", "AH", "N"],
  several: ["S", "EH", "V", "ER", "AH", "L"],
  share: ["SH", "EH", "R"],
  she: ["SH", "IY"],
  short: ["SH", "AO", "R", "T"],
  should: ["SH", "UH", "D"],
  side: ["S", "AY", "D"],
  sign: ["S", "AY", "N"],
  similar: ["S", "IH", "M", "AH", "L", "ER"],
  simple: ["S", "IH", "M", "P", "AH", "L"],
  since: ["S", "IH", "N", "S"],
  sister: ["S", "IH", "S", "T", "ER"],
  six: ["S", "IH", "K", "S"],
  size: ["S", "AY", "Z"],
  sleep: ["S", "L", "IY", "P"],
  slow: ["S", "L", "OW"],
  small: ["S", "M", "AO", "L"],
  smile: ["S", "M", "AY", "L"],
  snow: ["S", "N", "OW"],
  so: ["S", "OW"],
  some: ["S", "AH", "M"],
  someone: ["S", "AH", "M", "W", "AH", "N"],
  something: ["S", "AH", "M", "TH", "IH", "NG"],
  sometimes: ["S", "AH", "M", "T", "AY", "M", "Z"],
  son: ["S", "AH", "N"],
  soon: ["S", "UW", "N"],
  sound: ["S", "AW", "N", "D"],
  south: ["S", "AW", "TH"],
  speak: ["S", "P", "IY", "K"],
  special: ["S", "P", "EH", "SH", "AH", "L"],
  spend: ["S", "P", "EH", "N", "D"],
  spring: ["S", "P", "R", "IH", "NG"],
  stand: ["S", "T", "AE", "N", "D"],
  start: ["S", "T", "AA", "R", "T"],
  state: ["S", "T", "EY", "T"],
  stay2: ["S", "T", "EY"],
  step: ["S", "T", "EH", "P"],
  still2: ["S", "T", "IH", "L"],
  story: ["S", "T", "AO", "R", "IY"],
  street: ["S", "T", "R", "IY", "T"],
  student: ["S", "T", "UW", "D", "AH", "N", "T"],
  study: ["S", "T", "AH", "D", "IY"],
  such: ["S", "AH", "CH"],
  suddenly: ["S", "AH", "D", "AH", "N", "L", "IY"],
  summer: ["S", "AH", "M", "ER"],
  sun: ["S", "AH", "N"],
  supply: ["S", "AH", "P", "L", "AY"],
  support: ["S", "AH", "P", "AO", "R", "T"],
  sure: ["SH", "UH", "R"],
  sweet: ["S", "W", "IY", "T"],
  take: ["T", "EY", "K"],
  taste: ["T", "EY", "S", "T"],
  teach: ["T", "IY", "CH"],
  teacher: ["T", "IY", "CH", "ER"],
  team: ["T", "IY", "M"],
  tell: ["T", "EH", "L"],
  test: ["T", "EH", "S", "T"],
  thank2: ["TH", "AE", "NG", "K"],
  thanks: ["TH", "AE", "NG", "K", "S"],
  these2: ["DH", "IY", "Z"],
  think2: ["TH", "IH", "NG", "K"],
  thousand2: ["TH", "AW", "Z", "AH", "N", "D"],
  three2: ["TH", "R", "IY"],
  thursday2: ["TH", "ER", "Z", "D", "EY"],
  time: ["T", "AY", "M"],
  to: ["T", "UW"],
  today: ["T", "AH", "D", "EY"],
  tomorrow: ["T", "AH", "M", "AA", "R", "OW"],
  tonight: ["T", "AH", "N", "AY", "T"],
  too: ["T", "UW"],
  top: ["T", "AA", "P"],
  toward: ["T", "AO", "R", "D"],
  town: ["T", "AW", "N"],
  travel: ["T", "R", "AE", "V", "AH", "L"],
  travelers: ["T", "R", "AE", "V", "AH", "L", "ER", "Z"],
  tree: ["T", "R", "IY"],
  try: ["T", "R", "AY"],
  turn: ["T", "ER", "N"],
  twelve: ["T", "W", "EH", "L", "V"],
  twenty: ["T", "W", "EH", "N", "T", "IY"],
  two: ["T", "UW"],
  under: ["AH", "N", "D", "ER"],
  understand: ["AH", "N", "D", "ER", "S", "T", "AE", "N", "D"],
  until: ["AH", "N", "T", "IH", "L"],
  up: ["AH", "P"],
  upon: ["AH", "P", "AA", "N"],
  us: ["AH", "S"],
  use: ["Y", "UW", "Z"],
  usual: ["Y", "UW", "ZH", "AH", "W", "AH", "L"],
  vacation: ["V", "EY", "K", "EY", "SH", "AH", "N"],
  visit: ["V", "IH", "Z", "AH", "T"],
  voice2: ["V", "OY", "S"],
  vote: ["V", "OW", "T"],
  wait: ["W", "EY", "T"],
  walk: ["W", "AO", "K"],
  warm2: ["W", "AO", "R", "M"],
  watch: ["W", "AA", "CH"],
  way: ["W", "EY"],
  we: ["W", "IY"],
  weak: ["W", "IY", "K"],
  wear2: ["W", "EH", "R"],
  weekend: ["W", "IY", "K", "EH", "N", "D"],
  west2: ["W", "EH", "S", "T"],
  whether: ["W", "EH", "DH", "ER"],
  which: ["W", "IH", "CH"],
  while: ["W", "AY", "L"],
  who: ["HH", "UW"],
  whole: ["HH", "OW", "L"],
  whose: ["HH", "UW", "Z"],
  why: ["W", "AY"],
  wide: ["W", "AY", "D"],
  wife: ["W", "AY", "F"],
  will: ["W", "IH", "L"],
  win2: ["W", "IH", "N"],
  wind: ["W", "IH", "N", "D"],
  wish: ["W", "IH", "SH"],
  with: ["W", "IH", "DH"],
  within: ["W", "IH", "DH", "IH", "N"],
  without: ["W", "IH", "TH", "AW", "T"],
  woman: ["W", "UH", "M", "AH", "N"],
  women: ["W", "IH", "M", "AH", "N"],
  wonder: ["W", "AH", "N", "D", "ER"],
  wood: ["W", "UH", "D"],
  word: ["W", "ER", "D"],
  world: ["W", "ER", "L", "D"],
  worry: ["W", "ER", "IY"],
  would: ["W", "UH", "D"],
  write: ["R", "AY", "T"],
  wrong2: ["R", "AO", "NG"],
  yesterday: ["Y", "EH", "S", "T", "ER", "D", "EY"],
  yet2: ["Y", "EH", "T"],
  young2: ["Y", "AH", "NG"],
  zero: ["Z", "IH", "R", "OW"],
  zone: ["Z", "OW", "N"],

  // Misc top-frequency / common-conversational
  please2: ["P", "L", "IY", "Z"],
  yeah: ["Y", "EH"],
  oh: ["OW"],
  hi: ["HH", "AY"],
  bye: ["B", "AY"],
  goodbye: ["G", "UH", "D", "B", "AY"],
  morning2: ["M", "AO", "R", "N", "IH", "NG"],
  afternoon: ["AE", "F", "T", "ER", "N", "UW", "N"],
  night2: ["N", "AY", "T"],
  food2: ["F", "UW", "D"],
  hotel: ["HH", "OW", "T", "EH", "L"],
  airport: ["EH", "R", "P", "AO", "R", "T"],
  train: ["T", "R", "EY", "N"],
  bus: ["B", "AH", "S"],
  taxi: ["T", "AE", "K", "S", "IY"],
  ticket: ["T", "IH", "K", "AH", "T"],
  passport: ["P", "AE", "S", "P", "AO", "R", "T"],
  station: ["S", "T", "EY", "SH", "AH", "N"],
  restaurant: ["R", "EH", "S", "T", "ER", "AA", "N", "T"],
  shop: ["SH", "AA", "P"],
  market2: ["M", "AA", "R", "K", "AH", "T"],
  street2: ["S", "T", "R", "IY", "T"],
  computer: ["K", "AH", "M", "P", "Y", "UW", "T", "ER"],
  email: ["IY", "M", "EY", "L"],
  internet: ["IH", "N", "T", "ER", "N", "EH", "T"],
  number2: ["N", "AH", "M", "B", "ER"],
  thirteen2: ["TH", "ER", "T", "IY", "N"],
  forty: ["F", "AO", "R", "T", "IY"],
  fifty: ["F", "IH", "F", "T", "IY"],
  sixty: ["S", "IH", "K", "S", "T", "IY"],
  seventy: ["S", "EH", "V", "AH", "N", "T", "IY"],
  eighty: ["EY", "T", "IY"],
  ninety: ["N", "AY", "N", "T", "IY"],
  monday: ["M", "AH", "N", "D", "EY"],
  tuesday: ["T", "UW", "Z", "D", "EY"],
  wednesday: ["W", "EH", "N", "Z", "D", "EY"],
  friday: ["F", "R", "AY", "D", "EY"],
  sunday: ["S", "AH", "N", "D", "EY"],
  january: ["JH", "AE", "N", "Y", "UW", "EH", "R", "IY"],
  february: ["F", "EH", "B", "R", "UW", "EH", "R", "IY"],
  march: ["M", "AA", "R", "CH"],
  april: ["EY", "P", "R", "AH", "L"],
  may: ["M", "EY"],
  june: ["JH", "UW", "N"],
  july: ["JH", "UH", "L", "AY"],
  august: ["AO", "G", "AH", "S", "T"],
  september: ["S", "EH", "P", "T", "EH", "M", "B", "ER"],
  october: ["AA", "K", "T", "OW", "B", "ER"],
  november: ["N", "OW", "V", "EH", "M", "B", "ER"],
  december: ["D", "IH", "S", "EH", "M", "B", "ER"],
  cofee: ["K", "AO", "F", "IY"],
  hello2: ["HH", "AH", "L", "OW"],
  goodmorning: ["G", "UH", "D", "M", "AO", "R", "N", "IH", "NG"],
  yesterday2: ["Y", "EH", "S", "T", "ER", "D", "EY"],

  // Misc drill-only stragglers (extra coverage)
  rough: ["R", "AH", "F"],
  kept: ["K", "EH", "P", "T"],
  forest2: ["F", "AO", "R", "AH", "S", "T"],
  cheap2: ["CH", "IY", "P"],
  fits: ["F", "IH", "T", "S"],
  difference: ["D", "IH", "F", "ER", "AH", "N", "S"],
  warmed: ["W", "AO", "R", "M", "D"],
  velvet2: ["V", "EH", "L", "V", "AH", "T"],
  cheap3: ["CH", "IY", "P"],
  imports: ["IH", "M", "P", "AO", "R", "T", "S"],
  contracts: ["K", "AA", "N", "T", "R", "AE", "K", "T", "S"],
  records: ["R", "EH", "K", "ER", "D", "Z"],
  presents: ["P", "R", "EH", "Z", "AH", "N", "T", "S"],
  objects: ["AA", "B", "JH", "EH", "K", "T", "S"],
  test2: ["T", "EH", "S", "T"],
  message: ["M", "EH", "S", "AH", "JH"],
  ok2: ["OW", "K", "EY"],
};
