// AUTO-GENERATED by tools/tts-generate.py — do not hand-edit.
// Maps djb2(text + "|" + voiceId) → require() of bundled MP3.
// The mobile runtime computes the same hash via lib/tts-cache.ts:hashText.


export const AUDIO_INDEX: Record<string, () => any> = {
  "448489b2": () => require("./vc_default/448489b2.mp3"),
  "63eb5c2b": () => require("./vc_default/63eb5c2b.mp3"),
  "6e5990c7": () => require("./vc_default/6e5990c7.mp3"),
  "72b8580e": () => require("./vc_default/72b8580e.mp3"),
  "b823ab15": () => require("./vc_default/b823ab15.mp3"),
};
