// AUTO-GENERATED by tools/tts-generate.py — do not hand-edit.
// Maps djb2(text + "|" + voiceId) → require() of bundled MP3.
// The mobile runtime computes the same hash via lib/tts-cache.ts:hashText.
//
// Stub: empty until the Python script runs locally. With an empty index
// the runtime falls through to expo-speech (Siri) — same behaviour as
// before this change.

export const AUDIO_INDEX: Record<string, () => any> = {};
